In [1]:
import pandas as pd

In [2]:
df = pd.read_csv("Combined_dataset.csv")

In [3]:
df.head()

,product_id,title,product_description,rating,ratings_count,initial_price,discount,final_price,currency,images,...,amount_of_stars,what_customers_said,seller_name,sizes,videos,seller_information,variations,best_offer,more_offers,category
0,8376765,Lino Perros,Women Navy Blue Solid Backpack,3.8,15,3995,58.0,"""₹3,995.00""",INR,http://assets.myntassets.com/assets/images/837...,...,"{""1_star"":2,""2_stars"":0,""3_stars"":3,""4_stars"":...",NaN,NaN,"[{""size"":""Onesize""}]","[""rw-8376765_cae700""]",NaN,[{}],{},"[{""offer_name"":""10% Instant Discount on Citi C...",backpacks
1,9136281,Tommy Hilfiger,Unisex Navy Blue Striped Backpack,4.5,67,2899,35.0,"""₹2,899.00""",INR,http://assets.myntassets.com/assets/images/913...,...,"{""1_star"":3,""2_stars"":4,""3_stars"":2,""4_stars"":...",NaN,NaN,"[{""size"":""Onesize""}]","[""rw-9136281_cae700""]",NaN,"[{},{}]",{},"[{""offer_name"":""10% Instant Discount on Citi C...",backpacks
2,17633752,Lavie,Aries Women Pink Mini Backpack,4.4,226,2999,65.0,"""₹2,999.00""",INR,http://assets.myntassets.com/assets/images/176...,...,"{""1_star"":9,""2_stars"":5,""3_stars"":10,""4_stars""...",NaN,NaN,"[{""size"":""S""}]","[""https://videos.myntassets.com/assets/videos/...",NaN,"[{},{},{},{},{},{}]",{},"[{""offer_name"":""10% Instant Discount on Citi C...",backpacks
3,1376949,F Gear,Unisex Navy & Grey Printed Burner Backpack,4.4,1052,1675,52.0,"""₹1,675.00""",INR,http://assets.myntassets.com/assets/images/137...,...,"{""1_star"":33,""2_stars"":21,""3_stars"":69,""4_star...",NaN,NaN,"[{""size"":""Onesize""}]","[""https://videos.myntassets.com/assets/videos/...",NaN,NaN,{},"[{""offer_name"":""10% Instant Discount on Citi C...",backpacks
4,13939916,MYTRIDENT,Men Blue Solid Bath Robe,4.7,12,2899,17.0,"""₹2,899.00""",INR,http://assets.myntassets.com/assets/images/pro...,...,"{""1_star"":0,""2_stars"":0,""3_stars"":0,""4_stars"":...",NaN,NaN,"[{""size"":""M"",""value"":""45.0in"",""value_name"":""Fr...",NaN,NaN,"[{},{},{},{},{},{},{},{},{},{},{},{},{},{}]",{},"[{""offer_name"":""10% Instant Discount on IndusI...",bath-robe

In [4]:
df.shape

(1000, 24)

In [5]:
df.columns

Index(['product_id', 'title', 'product_description', 'rating', 'ratings_count',
       'initial_price', 'discount', 'final_price', 'currency', 'images',
       'delivery_options', 'product_details', 'breadcrumbs',
       'product_specifications', 'amount_of_stars', 'what_customers_said',
       'seller_name', 'sizes', 'videos', 'seller_information', 'variations',
       'best_offer', 'more_offers', 'category'],
      dtype='object')

In [6]:
df.dtypes

product_id                  int64
title                      object
product_description        object
rating                    float64
ratings_count               int64
initial_price               int64
discount                  float64
final_price                object
currency                   object
images                     object
delivery_options           object
product_details            object
breadcrumbs                object
product_specifications     object
amount_of_stars            object
what_customers_said        object
seller_name                object
sizes                      object
videos                     object
seller_information         object
variations                 object
best_offer                 object
more_offers                object
category                   object
dtype: object

In [7]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 24 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   product_id              1000 non-null   int64
 1   title                   1000 non-null   object
 2   product_description     1000 non-null   object
 3   rating                  1000 non-null   float64
 4   ratings_count           1000 non-null   int64
 5   initial_price           1000 non-null   int64
 6   discount                879 non-null    float64
 7   final_price             1000 non-null   object
 8   currency                1000 non-null   object
 9   images                  1000 non-null   object
 10  delivery_options        1000 non-null   object
 11  product_details         1000 non-null   object
 12  breadcrumbs             1000 non-null   object
 13  product_specifications  1000 non-null   object
 14  amount_of_stars         1000 non-null   object
 15  what_customers_said     427 non-null    object
 16  seller_name             699 non-null    object
 17  sizes                   1000 non-null   object
 18  videos                  219 non-null    object
 19  seller_information      699 non-null    object
 20  variations              438 non-null    object
 21  best_offer              1000 non-null   object
 22  more_offers             1000 non-null   object
 23  category                1000 non-null   object
dtypes: float64(2), int64(3), object(19)
memory usage: 187.6+ KB

In [8]:
df.isnull().sum()

product_id                  0
title                       0
product_description         0
rating                      0
ratings_count               0
initial_price               0
discount                  121
final_price                 0
currency                    0
images                      0
delivery_options            0
product_details             0
breadcrumbs                 0
product_specifications      0
amount_of_stars             0
what_customers_said       573
seller_name               301
sizes                       0
videos                    781
seller_information        301
variations                562
best_offer                  0
more_offers                 0
category                    0
dtype: int64

In [9]:
df["discount"].fillna(df["discount"].median(), inplace=True)

C:\Users\harsh\AppData\Local\Temp\ipykernel_2688\959833209.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df["discount"].fillna(df["discount"].median(), inplace=True)

In [10]:
df["discount"] = df["discount"].fillna(df["discount"].median())

In [11]:
cols = [
    "what_customers_said",
    "seller_name",
    "videos",
    "seller_information",
    "variations"
]

df[cols] = df[cols].fillna("Not Available")

In [12]:
df.isnull().sum()

product_id                0
title                     0
product_description       0
rating                    0
ratings_count             0
initial_price             0
discount                  0
final_price               0
currency                  0
images                    0
delivery_options          0
product_details           0
breadcrumbs               0
product_specifications    0
amount_of_stars           0
what_customers_said       0
seller_name               0
sizes                     0
videos                    0
seller_information        0
variations                0
best_offer                0
more_offers               0
category                  0
dtype: int64

In [13]:
df.duplicated().sum()

np.int64(0)

In [14]:
df = df.drop_duplicates()

In [15]:
df.shape

(1000, 24)

In [16]:
df["total_amount"] = df["initial_price"] * df["ratings_count"]

df[["title","initial_price","ratings_count","total_amount"]].head()

            title  initial_price  ratings_count  total_amount
0     Lino Perros           3995             15         59925
1  Tommy Hilfiger           2899             67        194233
2           Lavie           2999            226        677774
3          F Gear           1675           1052       1762100
4       MYTRIDENT           2899             12         34788

In [17]:
df.to_csv("cleaned_fashion_products.csv", index=False)

In [18]:
import os
os.listdir()

['.ipynb_checkpoints',
 'Basic_Data_Cleaning.ipynb',
 'cleaned_fashion_products.csv',
 'Combined_dataset.csv']